import type { Metadata } from "next";
import "../styles/globals.css";
import SideMenu from "@/components/SideMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sp">
      <body>
        <SideMenu />
        <div className="content-container">{children}</div>
      </body>
    </html>
  );
}
